Try to fix github CI test issue with pyvista
- Got this error, apparently something has changed in pyvista:
  AttributeError: module 'pyvista' has no attribute 'UniformGrid'
  Force to install previous pyvista version as a fix.
  Now testing is done with numpy vtk==9.2.6 pyvista==0.42.3